image: node:latest

cache:
  paths: 
    - node_modules/

variables:
  NODE_ENV: 'production'

pages: 
  script: 
    - npm ci
    - npm run build
  artifacts: 
    paths: 
      - public
  only: 
    - master