name: Deploy Hostings

on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: set account identity 
      run: |
        git config --global user.email "askalburgi@gamil.com"
        git config --global user.name "Arjun Kalburgi"
    - name: npm install & deploy
      run: |
        npm install
        npm run deploy --if-present
      env:
        CI: true
